version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: vkmarket
      POSTGRES_USER: vkuser
      POSTGRES_PASSWORD: vkpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vkuser -d vkmarket" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
          condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: vkuser
      DB_PASSWORD: vkpass
      DB_NAME: vkmarket
      JWT_SECRET: secret
    ports:
      - "8080:8080"
    command: ["./app"]
    restart: always


volumes:
  pgdata: 